# !/usr/bin/python3
"""
CONSTANTS PROJECT
"""
# Import necessary fonts
AIRLINE_NAMES = {
    "TU": "TUNISAIR",
    "AF": "AIR FRANCE",
    "BJ": "NOUVELAIR",
    "HV": "TRANSAVIA",
}
FLIGHT_STATUS = ["scheduled", "cancelled", "active", "landed"]
TYPE_FLIGHTS = ["DEPARTURE", "ARRIVAL"]
SQL_OPERATORS = ["MIN", "MAX", "AVG"]
FONT_SIZE = 20

# SQL Table
SQL_TABLE_NAME = "TUN_FLIGHTS"

FLIGHT_TABLE_COLUMNS = (
    "ID_FLIGHT",
    "DEPARTURE_DATE",
    "ARRIVAL_DATE",
    "FLIGHT_NUMBER",
    "FLIGHT_STATUS",
    "DEPARTURE_IATA",
    "DEPARTURE_AIRPORT",
    "ARRIVAL_IATA",
    "ARRIVAL_AIRPORT",
    "DEPARTURE_SCHEDULED",
    "DEPARTURE_HOUR",
    "ARRIVAL_SCHEDULED",
    "ARRIVAL_HOUR",
    "DEPARTURE_ESTIMATED",
    "ARRIVAL_ESTIMATED",
    "DEPARTURE_ACTUAL",
    "ARRIVAL_ACTUAL",
    "DEPARTURE_DELAY",
    "ARRIVAL_DELAY",
    "AIRLINE",
    "ARRIVAL_COUNTRY",
    "DEPARTURE_COUNTRY",
)

DEFAULT_TABLE = """
(
"ID_FLIGHT" TEXT NOT NULL,
"DEPARTURE_DATE" TEXT,
"ARRIVAL_DATE" TEXT,
"FLIGHT_NUMBER"	TEXT NOT NULL,
"FLIGHT_STATUS"	TEXT,
"DEPARTURE_IATA" TEXT,
"DEPARTURE_AIRPORT" TEXT,
"ARRIVAL_IATA" TEXT,
"ARRIVAL_AIRPORT" TEXT,
"DEPARTURE_SCHEDULED" TEXT,
"DEPARTURE_HOUR" INT,
"ARRIVAL_SCHEDULED" TEXT,
"ARRIVAL_HOUR" INT,
"DEPARTURE_ESTIMATED" TEXT,
"ARRIVAL_ESTIMATED" TEXT,
"DEPARTURE_ACTUAL" TEXT,
"ARRIVAL_ACTUAL" TEXT,
"DEPARTURE_DELAY" INT,
"ARRIVAL_DELAY" INT,
"AIRLINE" TEXT,
"ARRIVAl_COUNTRY" TEXT,
"DEPARTURE_COUNTRY" TEXT,
PRIMARY KEY("ID_FLIGHT")
)
"""
